package templatestests

import "context"

// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/validate
// gowrap: http://github.com/hexdigest/gowrap

//go:generate gowrap gen -p github.com/hexdigest/gowrap/templates_tests -i InterfaceWithValidtableArg -t ../templates/validate -o interface_with_validation.go -l ""

// InterfaceWithValidtableArgWithValidation implements InterfaceWithValidtableArg interface instrumented with arguments validation
type InterfaceWithValidtableArgWithValidation struct {
	InterfaceWithValidtableArg
}

// NewInterfaceWithValidtableArgWithValidation returns InterfaceWithValidtableArgWithValidation
func NewInterfaceWithValidtableArgWithValidation(base InterfaceWithValidtableArg) InterfaceWithValidtableArgWithValidation {
	return InterfaceWithValidtableArgWithValidation{
		InterfaceWithValidtableArg: base,
	}
}

// Method implements InterfaceWithValidtableArg
func (_d InterfaceWithValidtableArgWithValidation) Method(ctx context.Context, r *ValidatableRequest) (err error) {

	if _v, _ok := interface{}(r).(interface{ Validate() error }); _ok {
		if err = _v.Validate(); err != nil {
			return
		}
	}

	return _d.InterfaceWithValidtableArg.Method(ctx, r)
}
