// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/opentelemetry
// gowrap: http://github.com/hexdigest/gowrap

package templatestests

//go:generate gowrap gen -p github.com/hexdigest/gowrap/templates_tests -i TestInterface -t ../templates/opentelemetry -o interface_with_opentelemetry.go -v DecoratorName=TestInterfaceWithOpentelemetry -l ""

import (
	"context"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

// TestInterfaceWithOpentelemetry implements TestInterface interface instrumented with opentracing spans
type TestInterfaceWithOpentelemetry struct {
	TestInterface
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewTestInterfaceWithOpentelemetry returns TestInterfaceWithOpentelemetry
func NewTestInterfaceWithOpentelemetry(base TestInterface, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) TestInterfaceWithOpentelemetry {
	d := TestInterfaceWithOpentelemetry{
		TestInterface: base,
		_instance:     instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// F implements TestInterface
func (_d TestInterfaceWithOpentelemetry) F(ctx context.Context, a1 string, a2 ...string) (result1 string, result2 string, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "TestInterface.F")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"a1":  a1,
				"a2":  a2}, map[string]interface{}{
				"result1": result1,
				"result2": result2,
				"err":     err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.TestInterface.F(ctx, a1, a2...)
}
