// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/timeout
// gowrap: http://github.com/hexdigest/gowrap

package templatestests

//go:generate gowrap gen -p github.com/hexdigest/gowrap/templates_tests -i TestInterface -t ../templates/timeout -o interface_with_timeout.go -l ""

import (
	"context"
	"time"
)

// TestInterfaceWithTimeout implements TestInterface interface instrumented with timeouts
type TestInterfaceWithTimeout struct {
	TestInterface
	config TestInterfaceWithTimeoutConfig
}

type TestInterfaceWithTimeoutConfig struct {
	ContextNoErrorTimeout time.Duration

	FTimeout time.Duration
}

// NewTestInterfaceWithTimeout returns TestInterfaceWithTimeout
func NewTestInterfaceWithTimeout(base TestInterface, config TestInterfaceWithTimeoutConfig) TestInterfaceWithTimeout {
	return TestInterfaceWithTimeout{
		TestInterface: base,
		config:        config,
	}
}

// ContextNoError implements TestInterface
func (_d TestInterfaceWithTimeout) ContextNoError(ctx context.Context, a1 string, a2 string) {
	var cancelFunc func()
	if _d.config.ContextNoErrorTimeout > 0 {
		ctx, cancelFunc = context.WithTimeout(ctx, _d.config.ContextNoErrorTimeout)
		defer cancelFunc()
	}
	_d.TestInterface.ContextNoError(ctx, a1, a2)
	return
}

// F implements TestInterface
func (_d TestInterfaceWithTimeout) F(ctx context.Context, a1 string, a2 ...string) (result1 string, result2 string, err error) {
	var cancelFunc func()
	if _d.config.FTimeout > 0 {
		ctx, cancelFunc = context.WithTimeout(ctx, _d.config.FTimeout)
		defer cancelFunc()
	}
	return _d.TestInterface.F(ctx, a1, a2...)
}
