package templatestests

// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/twirp_validate
// gowrap: http://github.com/hexdigest/gowrap

//go:generate gowrap gen -p github.com/hexdigest/gowrap/templates_tests -i InterfaceWithValidtableArg -t ../templates/twirp_validate -o interface_with_twirp_validation.go -l ""

import (
	"context"

	"github.com/twitchtv/twirp"
)

// InterfaceWithValidtableArgWithTwirpValidation implements InterfaceWithValidtableArg interface instrumented with arguments validation
type InterfaceWithValidtableArgWithTwirpValidation struct {
	InterfaceWithValidtableArg
}

// NewInterfaceWithValidtableArgWithTwirpValidation returns InterfaceWithValidtableArgWithTwirpValidation
func NewInterfaceWithValidtableArgWithTwirpValidation(base InterfaceWithValidtableArg) InterfaceWithValidtableArgWithTwirpValidation {
	return InterfaceWithValidtableArgWithTwirpValidation{
		InterfaceWithValidtableArg: base,
	}
}

// Method implements InterfaceWithValidtableArg
func (_d InterfaceWithValidtableArgWithTwirpValidation) Method(ctx context.Context, r *ValidatableRequest) (err error) {

	if _v, _ok := interface{}(r).(interface{ Validate() error }); _ok {
		if err = _v.Validate(); err != nil {
			err = twirp.NewError(twirp.InvalidArgument, err.Error())
			return
		}
	}

	return _d.InterfaceWithValidtableArg.Method(ctx, r)
}
